%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/lalbert/Documents/Sunflower fluorescence proj/Second
%    sunflowers/clean LCF licor
%    files/clean/Light_curve_gray_03-24-15-cf_sunfl_plt2.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2015/12/12 03:27:10

%% Initialize variables.
filename = '/Users/lalbert/Documents/Sunflower fluorescence proj/Second sunflowers/clean LCF licor files/clean/Light_curve_gray_03-24-15-cf_sunfl_plt2.csv';
delimiter = ',';
startRow = 2;

%% Format string for each line of text:
%   column1: double (%f)
%	column2: text (%s)
%   column3: text (%s)
%	column4: text (%s)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: double (%f)
%	column16: double (%f)
%   column17: double (%f)
%	column18: double (%f)
%   column19: double (%f)
%	column20: double (%f)
%   column21: double (%f)
%	column22: double (%f)
%   column23: double (%f)
%	column24: double (%f)
%   column25: double (%f)
%	column26: double (%f)
%   column27: double (%f)
%	column28: double (%f)
%   column29: double (%f)
%	column30: double (%f)
%   column31: double (%f)
%	column32: double (%f)
%   column33: double (%f)
%	column34: double (%f)
%   column35: double (%f)
%	column36: double (%f)
%   column37: double (%f)
%	column38: double (%f)
%   column39: double (%f)
%	column40: double (%f)
%   column41: double (%f)
%	column42: double (%f)
%   column43: double (%f)
%	column44: double (%f)
%   column45: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%s%s%s%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
Obs1 = dataArray{:, 1};
HHMMSS1 = dataArray{:, 2};
Treatment1 = dataArray{:, 3};
leaf_tag_color1 = dataArray{:, 4};
plant_number1 = dataArray{:, 5};
FTime1 = dataArray{:, 6};
EBal1 = dataArray{:, 7};
Photo1 = dataArray{:, 8};
Cond1 = dataArray{:, 9};
Ci1 = dataArray{:, 10};
Trmmol1 = dataArray{:, 11};
VpdL1 = dataArray{:, 12};
CTleaf1 = dataArray{:, 13};
Area1 = dataArray{:, 14};
BLC_2 = dataArray{:, 15};
StmRat1 = dataArray{:, 16};
BLCond1 = dataArray{:, 17};
Tair1 = dataArray{:, 18};
Tleaf1 = dataArray{:, 19};
TBlk1 = dataArray{:, 20};
CO2R1 = dataArray{:, 21};
CO2S1 = dataArray{:, 22};
H2OR1 = dataArray{:, 23};
H2OS1 = dataArray{:, 24};
RH_R1 = dataArray{:, 25};
RH_S1 = dataArray{:, 26};
Flow1 = dataArray{:, 27};
PARi1 = dataArray{:, 28};
PARo1 = dataArray{:, 29};
Press1 = dataArray{:, 30};
CsMch1 = dataArray{:, 31};
HsMch1 = dataArray{:, 32};
StableF1 = dataArray{:, 33};
BLCslope1 = dataArray{:, 34};
BLCoffst1 = dataArray{:, 35};
f_parin1 = dataArray{:, 36};
f_parout1 = dataArray{:, 37};
alphaK1 = dataArray{:, 38};
Status1 = dataArray{:, 39};
Fo1 = dataArray{:, 40};
Fm1 = dataArray{:, 41};
Fs1 = dataArray{:, 42};
Fo_prime1 = dataArray{:, 43};
Fm_prime1 = dataArray{:, 44};
NPQ1 = dataArray{:, 45};


%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;